### ISSUE TITLE
Avoid new lines in bulleted lists

### ISSUE THREAD

**Issue by hturner** [rjournal/rjtools#102]
Following on from https://github.com/Abhi-1U/texor/issues/60, cc @ajrgodfrey.

Consider the following .Rmd

```
---
title: "bulleted list issues"
---

## Good bullets

- one
- two
- three

## Bad bullets

-   one blah

-   two what

-   three
```

When rendered to `html_document` the "bad" bullets have a blank line between each bullet point, which is read as "empty line" by screen readers.

When rendered to `rjtools::rjournal_web_article` both sets of bullet points have a blank line between each bullet point.

It would be good if the rjtools style did not introduce blank lines in the first case (and authors were encouraged to use this form). The blank lines appear to be due to `<p>` tags nested within `<li>` tags.

**Comment by dicook** [comment]
This is best handled by distill

**Comment by dicook** [comment]
Posted at https://github.com/rstudio/distill/issues/496#issue-1916677305

**Comment by cderv** [comment]
I made an answer in https://github.com/Abhi-1U/texor/issues/60#issuecomment-1738814673

In short: 

* `<p>` is added in HTML  because of the Loose list syntax by Pandoc (see pandoc.org/MANUAL.html#bullet-lists)
* if you want to enforce compact list, you could transform loose list to compact list through a Lua filter. 

> When rendered to rjtools::rjournal_web_article both sets of bullet points have a blank line between each bullet point.

I don't know why you get this. I'll comment on rstudio/distill#496 as for distill I don't think this is the case
